### ISSUE TITLE
很抱歉下载您的这一篇文章就不行

### ISSUE THREAD

**Issue by alexsaurora** [accforgit/JuejinDD#1]
插件报错Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
文章链接：https://juejin.cn/post/6908950170671513607?utm_source=gold_browser_extension

**Comment by accforgit** [comment]
安装好插件后，刷新一下文章页面




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "accforgit/JuejinDD"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月22日(星期二) 下午5:59
收件人:&nbsp;"accforgit/JuejinDD"<JuejinDD@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[accforgit/JuejinDD] 很抱歉下载您的这一篇文章就不行 (#1)





 
插件报错Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.
 文章链接：https://juejin.cn/post/6908950170671513607?utm_source=gold_browser_extension

**Comment by accforgit** [comment]
安装完插件后，要先刷新一下文章页面，否则插件会报错，只需要在第一次安装的时候刷新，以后就不用了；如果你重新reload了一遍插件，那么也需要刷新文章详情页面后才可以

**Comment by alexsaurora** [comment]
可以下载了，大佬好cool～
